sso:
  user: 'SY2000000' # 统一认证学号/工号
  passwd: '********' # 统一认证密码
alipay:
  user: '13311313133' # 支付宝账号（手机号）
  passwd: '******' # 支付密码（非登陆密码）

priority: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] # 场地优先级
reserve_time: [14, 15] # 预约时间，24小时制。以小时开始时为代表，如[14, 15]则代表预约14-16
candidate: 1 # 第几候选同伴